# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d470cbd35f51ecfa34fbd9b850c9004c20905ce7e9aa46df9a054125bd6d45c37995b1e13fbeac1739c6434be05c10e914ddb51406d42f075a16f351420519b

test:
  secret_key_base: 960fbedbfa8c3084fc1ee659561756589929f9aa257eff202b4919fb20e481c15357a2be9305a02de137d99880f6bb4fcad6eb00755b060d2e061997640378ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
